### ISSUE TITLE
flexible scaling for y-axis and threshold

### ISSUE THREAD

**Issue by ceenell** [USGS-VIZLAB/forecast-drb#7]
We want some way to have the threshold line appear when temperature values are within range of the threshold. Ideally the axis text and ticks are the same color.

**Comment by aaarchmiller** [comment]
Example with dynamically color `axis.text` here: https://stackoverflow.com/questions/49076565/r-ggplot-how-can-i-create-conditional-labeling-for-a-continuous-axis-ticks
